language: go
script: make build-dev
services:
- docker
before_install: make docker-build
before_deploy: tar -cvzf graphite-writer-stats.tar.gz ./graphite-writer-stats
deploy:
  provider: releases
  api_key:
    secure: "m+zbIWEb9bdUsGS194ROiLujaEMhr8LPi4xJVzspRGT2Gh7Lq0bnZL/njrDtDuLQ6DM3Jy8Gh0atpGAoi0HC3v6EQZrqeGFnRD2RfHeaWJj/GaLLoc2zT+9CinYkPSb6kdMeK4uh4Y9ZVfejGPHRs8Xfdxl+QstdzhjJV+40wW56WA/i8yvy0xR1WPu32RSa8L2tbLkB3QJHVoZpiIKsBkmyS+7WyBUK4gPWZsWt0+LIs4xSRnZJJKXIakgdB/P1z8O25l5AImlXEX57/7aEXuXyha25fqoIDcQ6zRUbTSdEaQnTQ5KPM7wrCbn+R0e5zyfP5AIRCZtU/YTo83s/aU1SBQrCoLMBBSTcJDvATaSJTvzcjOaGKJskAai+BuYNivA++tQAJ+mA3qaxvTa1BQJ7u4FctgzCXx82SsoFDD7hGdDIUwGgDxzOQ49NQhPtrCuDMwn1pQ/XIg7UYJ81krBSSpTBgMKhgQdBDQg3/ILKyMcx/G+c3h+akfa2ueXqIpGNA7kSKJwtbo1rCd7fC+l50SA4GHP+Ip6SAxtsgyDQtSytM+E7V4fbuXyhKIceyViFFzCEGYeJlhGFILc0k8N3xEk4csh0lGeDOnQ104ADA2+Ritb+MZ4YfGM4fp4eleI6Aw06juj/4Tk6FckL8UlyDHVgn0B+rfPWDe939Z4="
  file: graphite-writer-stats.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: criteo/graphite-writer-stats
